@ECHO OFF
"C:\Program Files\Atmel\AVR Tools\AvrAssembler2\avrasm2.exe" -S "C:\YANDEX\AVR_PROJECT\IR_TO_UART\labels.tmp" -fI -W+ie -C V2 -o "C:\YANDEX\AVR_PROJECT\IR_TO_UART\IR_TO_UART.hex" -d "C:\YANDEX\AVR_PROJECT\IR_TO_UART\IR_TO_UART.obj" -e "C:\YANDEX\AVR_PROJECT\IR_TO_UART\IR_TO_UART.eep" -m "C:\YANDEX\AVR_PROJECT\IR_TO_UART\IR_TO_UART.map" "C:\YANDEX\AVR_PROJECT\IR_TO_UART\IR_TO_UART.asm"
